[package]
name = "stride"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = "0.10.1"
gtk4-layer-shell = "0.6.3"
rodio = { version = "0.21.1", default-features = false, features = ["playback"] }

[profile.release]
lto = true
strip = true
panic = "abort"
